name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - master

variables:
  workingDirectoryFolder: $(System.DefaultWorkingDirectory)
  kubernetesServiceEndpoint: aksstartup-aks

stages:
- stage: Continuous_Integration
  displayName: Continuous Integration
  pool:
     vmImage: ubuntu-latest
  jobs:

  - job: build_push
    displayName: Build and push
    steps:

    - bash: |
        ls -al
      displayName: List files in $(workingDirectoryFolder)
      workingDirectory: $(workingDirectoryFolder)
      failOnStderr: true

    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: aksstartup-acr

    - task: Docker@2
      displayName: Build and build
      inputs:
        command: buildAndPush
        containerRegistry: aksstartup-acr
        repository: 'aks-startup-dotnet-app'
        Dockerfile: 'Dockerfile'
        tags: 'latest'

  - job: DeploytoAKS
    dependsOn: build_push
    displayName: Deploy to AKS
    steps:

    - bash: |
        ls -al
      displayName: List files in $(workingDirectoryFolder)
      workingDirectory: $(workingDirectoryFolder)
      failOnStderr: true

    - task: HelmDeploy@0
      displayName: Helm list
      inputs:
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
        command: ls
        arguments: --all

    - task: Kubernetes@1
      displayName: kubectl login
      inputs:
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
        command: login

    - bash: |
        helm template aks-startup-app .
        helm upgrade --install aks-startup-app .
      displayName: helm upgrade --install
      workingDirectory: $(workingDirectoryFolder)/helm
      failOnStderr: false  
