version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
    restart: always
    container_name: mssql-1
    environment:
      SA_PASSWORD: "Secret1234"
      ACCEPT_EULA: "Y"
    ports: 
      - 9200:1433
    volumes:
        - datastore:/var/opt/mssql
    networks:
      - aks_startup_common_network
networks:
  aks_startup_common_network:
    name: aks_startup_common_network
    external: true
volumes:
  kestrel_certificate: {}    
  datastore: {}    
